load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "googletest",
  urls = ["https://github.com/google/googletest/archive/refs/tags/release-1.11.0.zip"],
  sha256 = "353571c2440176ded91c2de6d6cd88ddd41401d14692ec1f99e35d013feda55a",
  strip_prefix = "googletest-release-1.11.0"
)

http_archive(
  name = "argh",
  urls = ["https://github.com/shrimpster00/argh/archive/refs/tags/release-0.2.0.zip"],
  strip_prefix = "argh-release-0.2.0/src",
)
